version: '2'
services:
  gamesonlineshop-app:
    image: gamesonlineshop
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gamesonlineshop-postgresql:5432/GamesOnlineShop
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://gamesonlineshop-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://gamesonlineshop-elasticsearch:9200
    ports:
      - 8080:8080
  gamesonlineshop-postgresql:
    extends:
      file: postgresql.yml
      service: gamesonlineshop-postgresql
  gamesonlineshop-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: gamesonlineshop-elasticsearch
